from spotipy.oauth2 import SpotifyOAuth
import spotipy
import base64
import io
import os
from PIL import Image

sp_oauth = SpotifyOAuth(
    client_id=os.getenv("SPOTIPY_CLIENT_ID"),
    client_secret=os.getenv("SPOTIPY_CLIENT_SECRET"),
    redirect_uri=os.getenv("SPOTIPY_REDIRECT_URI"),
    scope="playlist-modify-public user-read-private ugc-image-upload"
)

def get_spotify_client(access_token):
    return spotipy.Spotify(auth=access_token)

def search_track_on_spotify(sp, query):
    if " - " in query:
        title, artist = [x.strip() for x in query.split(" - ", 1)]
        results = sp.search(q=f'track:"{title}" artist:"{artist}"', type='track', limit=1)
        if results['tracks']['items']:
            return results['tracks']['items'][0]['uri']

    # fallback search
    results = sp.search(q=query, type='track', limit=1)
    if results['tracks']['items']:
        return results['tracks']['items'][0]['uri']

    return None

def set_playlist_cover(sp, playlist_id, image_path):
    # resize and compress
    try:
        with Image.open(image_path) as img:
            img = img.convert('RGB')
            img.thumbnail((300, 300))
            buffer = io.BytesIO()
            img.save(buffer, format='JPEG', quality=85)
            image_b64 = base64.b64encode(buffer.getvalue()).decode('utf-8')
        sp.playlist_upload_cover_image(playlist_id, image_b64)
    except Exception:
        pass  # if fail


def create_playlist_from_song_list(sp, user_id, playlist_name, track_uris):
    # create empty playlist then populate with track URIs
    playlist = sp.user_playlist_create(
        user=user_id,
        name=playlist_name,
        public=True,
        description="Generated by Photo2Playlist"
    )
    sp.playlist_add_items(playlist_id=playlist['id'], items=track_uris)
    return playlist['external_urls']['spotify'], playlist['id']
